server:
  port: 8090
  servlet:
    context-path: /springcloudeureka

spring:
  application:
    name: spring-cloud-eureka

eureka:
  instance:
    hostname: localhost
  client:
    #表示是否注册自身到Eureka服务器
    register-with-eureka: false
    #表示是否从Eureka服务器上获取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/springcloudeureka/eureka/
