server:
  port: 8085
  servlet:
    context-path: /springbootconsumer

spring:
  application:
    name: spring-boot-consumer-hystrix

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/springcloudeureka/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #Hystrix超时时间，默认为1秒
            timeoutInMilliseconds: 3000
