server:
  port: 8091
  servlet:
    context-path: /springcloudzuul

spring:
  application:
    name: spring-cloud-zuul

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/springcloudeureka/eureka/

zuul:
  routes:
    zuul-a:
      path: /zuul-a/**
      serviceId: spring-boot-provider
      #url: http://localhost:8081/springbootprovider
    zuul-b:
      path: /zuul-b/**
      serviceId: spring-boot-provider
      #url: http://localhost:8083/springbootprovider
