server:
  port: 8083
  servlet:
    context-path: /springbootprovider

spring:
  application:
    name: spring-boot-provider

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8090/springcloudeureka/eureka/
